"""Deterministic text analysis used by every module (and by the mock AI examiners).

These measurements are computed locally - never by an LLM - so figures such as word count,
lexical diversity or linking-device usage are exact and reproducible.
"""

from __future__ import annotations

import re
from collections import Counter
from dataclasses import dataclass

_WORD = re.compile(r"[A-Za-z0-9]+(?:['’\-][A-Za-z0-9]+)*")
_SENTENCE_SPLIT = re.compile(r"(?<=[.!?])[\"')\]]*\s+(?=[\"'(\[]?[A-Z0-9])")
_ABBREVIATIONS = ("e.g.", "i.e.", "etc.", "Mr.", "Mrs.", "Ms.", "Dr.", "vs.", "approx.", "St.", "No.")

STOPWORDS = frozenset(
    [
        "a",
        "about",
        "above",
        "after",
        "again",
        "against",
        "all",
        "also",
        "am",
        "an",
        "and",
        "any",
        "are",
        "as",
        "at",
        "be",
        "because",
        "been",
        "before",
        "being",
        "below",
        "between",
        "both",
        "but",
        "by",
        "can",
        "could",
        "did",
        "do",
        "does",
        "doing",
        "down",
        "during",
        "each",
        "few",
        "for",
        "from",
        "further",
        "had",
        "has",
        "have",
        "having",
        "he",
        "her",
        "here",
        "hers",
        "herself",
        "him",
        "himself",
        "his",
        "how",
        "i",
        "if",
        "in",
        "into",
        "is",
        "it",
        "its",
        "itself",
        "just",
        "let",
        "me",
        "more",
        "most",
        "my",
        "myself",
        "no",
        "nor",
        "not",
        "of",
        "off",
        "on",
        "once",
        "only",
        "or",
        "other",
        "our",
        "ours",
        "ourselves",
        "out",
        "over",
        "own",
        "same",
        "she",
        "should",
        "so",
        "some",
        "such",
        "than",
        "that",
        "the",
        "their",
        "theirs",
        "them",
        "themselves",
        "then",
        "there",
        "these",
        "they",
        "this",
        "those",
        "through",
        "to",
        "too",
        "under",
        "until",
        "up",
        "very",
        "was",
        "we",
        "were",
        "what",
        "when",
        "where",
        "which",
        "while",
        "who",
        "whom",
        "why",
        "will",
        "with",
        "would",
        "you",
        "your",
        "yours",
        "yourself",
        "yourselves",
        "one",
        "also",
        "many",
        "much",
        "may",
        "might",
        "must",
        "shall",
        "us",
        "get",
        "got",
        "can't",
        "don't",
        "doesn't",
        "isn't",
        "aren't",
        "wasn't",
        "weren't",
        "i'm",
        "it's",
        "that's",
        "there's",
        "they're",
        "we're",
        "you're",
        "i've",
        "we've",
        "they've",
        "won't",
        "wouldn't",
        "shouldn't",
        "couldn't",
        "didn't",
        "haven't",
        "hasn't",
        "hadn't",
        "really",
        "well",
        "like",
        "just",
        "yes",
        "ok",
        "okay",
        "um",
        "uh",
        "er",
        "erm",
        "ah",
        "oh",
        "hmm",
        "mm",
        "think",
        "know",
        "say",
        "said",
        "thing",
        "things",
        "lot",
        "lots",
        "way",
    ]
)

# A compact academic word list (headwords + frequent derived forms, original selection).
ACADEMIC_WORDS = frozenset(
    [
        "analyse",
        "analyze",
        "analysis",
        "approach",
        "area",
        "assess",
        "assessment",
        "assume",
        "assumption",
        "authority",
        "available",
        "benefit",
        "benefits",
        "concept",
        "consist",
        "consistent",
        "constitute",
        "context",
        "contract",
        "create",
        "creation",
        "data",
        "define",
        "definition",
        "derive",
        "distribute",
        "distribution",
        "economy",
        "economic",
        "environment",
        "environmental",
        "establish",
        "estimate",
        "evident",
        "evidence",
        "export",
        "factor",
        "factors",
        "finance",
        "financial",
        "formula",
        "function",
        "identify",
        "identity",
        "income",
        "indicate",
        "indication",
        "individual",
        "individuals",
        "interpret",
        "interpretation",
        "involve",
        "involvement",
        "issue",
        "issues",
        "labour",
        "legal",
        "legislation",
        "major",
        "method",
        "methods",
        "occur",
        "percent",
        "percentage",
        "period",
        "policy",
        "policies",
        "principle",
        "procedure",
        "process",
        "require",
        "requirement",
        "research",
        "respond",
        "response",
        "role",
        "section",
        "sector",
        "significant",
        "significantly",
        "similar",
        "similarly",
        "source",
        "specific",
        "structure",
        "theory",
        "vary",
        "variation",
        "variety",
        "achieve",
        "achievement",
        "acquire",
        "acquisition",
        "administration",
        "affect",
        "appropriate",
        "aspect",
        "assist",
        "category",
        "chapter",
        "commission",
        "community",
        "complex",
        "compute",
        "conclude",
        "conclusion",
        "conduct",
        "consequence",
        "consequences",
        "construct",
        "consume",
        "consumption",
        "credit",
        "culture",
        "cultural",
        "design",
        "distinct",
        "element",
        "equate",
        "evaluate",
        "evaluation",
        "feature",
        "final",
        "focus",
        "impact",
        "injury",
        "institute",
        "institution",
        "invest",
        "investment",
        "item",
        "journal",
        "maintain",
        "maintenance",
        "normal",
        "obtain",
        "participate",
        "participation",
        "perceive",
        "perception",
        "positive",
        "potential",
        "previous",
        "primary",
        "purchase",
        "range",
        "region",
        "regulate",
        "regulation",
        "relevant",
        "reside",
        "resource",
        "resources",
        "restrict",
        "restriction",
        "secure",
        "security",
        "seek",
        "select",
        "site",
        "strategy",
        "strategies",
        "survey",
        "text",
        "tradition",
        "traditional",
        "transfer",
        "alternative",
        "circumstance",
        "comment",
        "compensate",
        "component",
        "consent",
        "considerable",
        "constant",
        "constraint",
        "contribute",
        "contribution",
        "convene",
        "coordinate",
        "core",
        "corporate",
        "correspond",
        "criteria",
        "deduce",
        "demonstrate",
        "document",
        "dominate",
        "emphasis",
        "emphasise",
        "emphasize",
        "ensure",
        "exclude",
        "framework",
        "fund",
        "illustrate",
        "immigrate",
        "imply",
        "initial",
        "instance",
        "interact",
        "justify",
        "layer",
        "link",
        "locate",
        "maximise",
        "maximize",
        "minor",
        "negate",
        "outcome",
        "partner",
        "philosophy",
        "physical",
        "proportion",
        "publish",
        "react",
        "register",
        "rely",
        "remove",
        "scheme",
        "sequence",
        "shift",
        "specify",
        "sufficient",
        "task",
        "technical",
        "technique",
        "technology",
        "valid",
        "volume",
        "access",
        "adequate",
        "annual",
        "apparent",
        "approximate",
        "attitude",
        "attribute",
        "civil",
        "code",
        "commit",
        "communicate",
        "concentrate",
        "confer",
        "contrast",
        "cycle",
        "debate",
        "despite",
        "dimension",
        "domestic",
        "emerge",
        "error",
        "ethnic",
        "goal",
        "grant",
        "hence",
        "hypothesis",
        "implement",
        "implementation",
        "implication",
        "impose",
        "integrate",
        "integration",
        "internal",
        "investigate",
        "job",
        "label",
        "mechanism",
        "obvious",
        "occupy",
        "option",
        "output",
        "overall",
        "parallel",
        "parameter",
        "phase",
        "predict",
        "prediction",
        "principal",
        "prior",
        "professional",
        "project",
        "promote",
        "regime",
        "resolve",
        "retain",
        "series",
        "statistic",
        "statistics",
        "status",
        "stress",
        "subsequent",
        "sum",
        "summary",
        "undertake",
        "academic",
        "adjust",
        "alter",
        "amend",
        "aware",
        "capacity",
        "challenge",
        "challenges",
        "clause",
        "compound",
        "conflict",
        "consult",
        "contact",
        "decline",
        "discrete",
        "draft",
        "enable",
        "energy",
        "enforce",
        "entity",
        "equivalent",
        "evolve",
        "expand",
        "expansion",
        "expose",
        "external",
        "facilitate",
        "fundamental",
        "generate",
        "generation",
        "image",
        "liberal",
        "licence",
        "logic",
        "margin",
        "medical",
        "mental",
        "modify",
        "monitor",
        "network",
        "notion",
        "objective",
        "orient",
        "perspective",
        "precise",
        "prime",
        "psychology",
        "pursue",
        "ratio",
        "reject",
        "revenue",
        "stable",
        "style",
        "substitute",
        "sustainable",
        "sustainability",
        "symbol",
        "target",
        "transit",
        "trend",
        "version",
        "welfare",
        "whereas",
        "abstract",
        "accurate",
        "acknowledge",
        "aggregate",
        "allocate",
        "assign",
        "attach",
        "author",
        "bond",
        "brief",
        "capable",
        "cite",
        "cooperate",
        "discriminate",
        "display",
        "diverse",
        "diversity",
        "domain",
        "edit",
        "enhance",
        "estate",
        "exceed",
        "explicit",
        "federal",
        "fee",
        "flexible",
        "furthermore",
        "gender",
        "ignorance",
        "incentive",
        "incidence",
        "incorporate",
        "index",
        "inhibit",
        "initiate",
        "input",
        "instruct",
        "intelligence",
        "interval",
        "lecture",
        "migrate",
        "migration",
        "minimum",
        "ministry",
        "motive",
        "neutral",
        "nevertheless",
        "overseas",
        "precede",
        "presume",
        "rational",
        "recover",
        "reveal",
        "scope",
        "subsidy",
        "tape",
        "trace",
        "transform",
        "transport",
        "underlie",
        "utilise",
        "utilize",
        "consequently",
        "moreover",
        "therefore",
        "thus",
        "crucial",
        "essential",
        "vital",
        "substantial",
        "dramatically",
        "gradually",
        "steadily",
        "sharply",
        "fluctuate",
        "fluctuation",
        "peak",
        "plateau",
        "decrease",
        "increase",
        "proportion",
        "majority",
        "minority",
        "accessible",
        "infrastructure",
        "urban",
        "rural",
        "globalisation",
        "globalization",
        "innovation",
        "innovative",
        "productivity",
        "unemployment",
        "inequality",
        "legislation",
        "regulation",
        "advocate",
        "controversial",
        "detrimental",
        "beneficial",
        "inevitable",
        "widespread",
        "prevalent",
        "mitigate",
        "alleviate",
        "exacerbate",
        "undermine",
        "foster",
        "cultivate",
    ]
)

LINKERS: dict[str, tuple[str, ...]] = {
    "addition": ("furthermore", "moreover", "in addition", "additionally", "also", "besides", "what is more"),
    "contrast": (
        "however",
        "nevertheless",
        "nonetheless",
        "on the other hand",
        "whereas",
        "although",
        "even though",
        "despite",
        "in spite of",
        "while",
        "on the contrary",
        "conversely",
        "yet",
    ),
    "cause_effect": (
        "therefore",
        "consequently",
        "as a result",
        "thus",
        "hence",
        "because",
        "due to",
        "owing to",
        "as a consequence",
        "for this reason",
        "this means that",
        "leads to",
        "results in",
    ),
    "example": ("for example", "for instance", "such as", "to illustrate", "namely", "in particular"),
    "sequence": ("firstly", "first of all", "secondly", "thirdly", "finally", "lastly", "to begin with", "subsequently"),
    "conclusion": ("in conclusion", "to conclude", "to sum up", "in summary", "overall", "all in all", "to summarise"),
    "emphasis": ("indeed", "in fact", "clearly", "undoubtedly", "significantly", "notably", "above all"),
    "comparison": ("similarly", "likewise", "in the same way", "compared to", "compared with", "in comparison", "in contrast"),
}

SUBORDINATORS = (
    "because",
    "although",
    "though",
    "even though",
    "which",
    "who",
    "whom",
    "whose",
    "when",
    "while",
    "whereas",
    "if",
    "unless",
    "since",
    "so that",
    "in order to",
    "as long as",
    "provided that",
    "until",
    "after",
    "before",
    "once",
    "where",
    "whether",
    "despite the fact that",
)


def words(text: str) -> list[str]:
    return [w.lower().replace("’", "'") for w in _WORD.findall(text or "")]


def word_count(text: str) -> int:
    return len(_WORD.findall(text or ""))


def split_sentences(text: str) -> list[str]:
    text = (text or "").strip()
    if not text:
        return []
    protected = text
    for i, abbr in enumerate(_ABBREVIATIONS):
        protected = protected.replace(abbr, f"__ABBR{i}__")
    parts = []
    for paragraph in re.split(r"\n+", protected):
        paragraph = paragraph.strip()
        if paragraph:
            parts.extend(p.strip() for p in _SENTENCE_SPLIT.split(paragraph) if p.strip())
    restored = []
    for part in parts:
        for i, abbr in enumerate(_ABBREVIATIONS):
            part = part.replace(f"__ABBR{i}__", abbr)
        restored.append(part)
    return restored


def split_paragraphs(text: str) -> list[str]:
    text = (text or "").strip()
    if not text:
        return []
    blocks = [p.strip() for p in re.split(r"\n\s*\n", text) if p.strip()]
    if len(blocks) == 1:
        lines = [p.strip() for p in text.split("\n") if p.strip()]
        if len(lines) > 1:
            return lines
    return blocks


def content_words(tokens: list[str]) -> list[str]:
    return [t for t in tokens if t not in STOPWORDS and not t.isdigit() and len(t) > 2]


def stem(word: str) -> str:
    """A tiny suffix-stripping stemmer, good enough for overlap and usage detection."""
    w = word.lower()
    for suffix in (
        "ational",
        "ization",
        "isation",
        "fulness",
        "iveness",
        "ments",
        "ment",
        "ingly",
        "edly",
        "ities",
        "ity",
        "ings",
        "ing",
        "ies",
        "ied",
        "ers",
        "er",
        "est",
        "ed",
        "es",
        "ly",
        "s",
    ):
        if w.endswith(suffix) and len(w) - len(suffix) >= 3:
            base = w[: -len(suffix)]
            if suffix in ("ies", "ied"):
                base += "y"
            return base
    return w


def type_token_ratio(tokens: list[str]) -> float:
    return len(set(tokens)) / len(tokens) if tokens else 0.0


def mattr(tokens: list[str], window: int = 40) -> float:
    """Moving-average type-token ratio: lexical diversity that is robust to text length."""
    if not tokens:
        return 0.0
    if len(tokens) <= window:
        return type_token_ratio(tokens)
    ratios = [len(set(tokens[i : i + window])) / window for i in range(len(tokens) - window + 1)]
    return sum(ratios) / len(ratios)


def find_linkers(text: str) -> dict[str, list[str]]:
    lowered = f" {(text or '').lower()} "
    found: dict[str, list[str]] = {}
    for group, phrases in LINKERS.items():
        hits = []
        for phrase in phrases:
            count = len(re.findall(rf"(?<![a-z]){re.escape(phrase)}(?![a-z])", lowered))
            hits.extend([phrase] * count)
        if hits:
            found[group] = hits
    return found


def linker_counts(text: str) -> Counter:
    counter: Counter = Counter()
    for hits in find_linkers(text).values():
        counter.update(hits)
    return counter


def is_complex_sentence(sentence: str) -> bool:
    lowered = f" {sentence.lower()} "
    if ";" in sentence:
        return True
    for marker in SUBORDINATORS:
        if re.search(rf"(?<![a-z]){re.escape(marker)}(?![a-z])", lowered):
            return True
    # participle clauses such as "Having considered..., " or ", leading to"
    return bool(re.search(r"(^|, )(having|being|leading|resulting|considering)\b", lowered.strip()))


def repeated_content_words(tokens: list[str], min_count: int = 3, exclude: set[str] | None = None) -> list[tuple[str, int]]:
    exclude = exclude or set()
    counts = Counter(t for t in content_words(tokens) if t not in exclude)
    return [(w, c) for w, c in counts.most_common() if c >= min_count]


def keyword_coverage(source: str, response: str) -> float:
    """Share of the source's key content stems that appear in the response (relevance proxy)."""
    key = {stem(w) for w in content_words(words(source))}
    if not key:
        return 1.0
    present = {stem(w) for w in content_words(words(response))}
    return len(key & present) / len(key)


def academic_words(tokens: list[str]) -> list[str]:
    return [t for t in tokens if t in ACADEMIC_WORDS or stem(t) in ACADEMIC_STEMS]


ACADEMIC_STEMS = frozenset(stem(w) for w in ACADEMIC_WORDS)


@dataclass
class TextStats:
    word_count: int
    sentence_count: int
    paragraph_count: int
    avg_sentence_length: float
    lexical_diversity: float
    academic_word_count: int
    complex_sentence_ratio: float


def text_stats(text: str) -> TextStats:
    tokens = words(text)
    sentences = split_sentences(text)
    paragraphs = split_paragraphs(text)
    complex_count = sum(1 for s in sentences if is_complex_sentence(s))
    return TextStats(
        word_count=len(tokens),
        sentence_count=len(sentences),
        paragraph_count=len(paragraphs),
        avg_sentence_length=round(len(tokens) / len(sentences), 1) if sentences else 0.0,
        lexical_diversity=round(mattr(tokens), 3),
        academic_word_count=len(academic_words(tokens)),
        complex_sentence_ratio=round(complex_count / len(sentences), 3) if sentences else 0.0,
    )
