"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-08 10:16:50.315337+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('icon', sa.String(length=40), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('tier', sa.String(length=10), nullable=False),
    sa.Column('xp_reward', sa.Integer(), nullable=False),
    sa.Column('criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('hidden', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_achievements')),
    sa.UniqueConstraint('code', name=op.f('uq_achievements_code'))
    )
    op.create_table('grammar_exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seed_key', sa.String(length=80), nullable=True),
    sa.Column('topic', sa.String(length=40), nullable=False),
    sa.Column('qtype', sa.String(length=30), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('accepted', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('cefr', sa.String(length=4), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_grammar_exercises')),
    sa.UniqueConstraint('seed_key', name=op.f('uq_grammar_exercises_seed_key'))
    )
    op.create_index(op.f('ix_grammar_exercises_topic'), 'grammar_exercises', ['topic'], unique=False)
    op.create_table('speaking_topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seed_key', sa.String(length=80), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('topic', sa.String(length=80), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('questions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cue_card', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('part3_questions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_speaking_topics')),
    sa.UniqueConstraint('seed_key', name=op.f('uq_speaking_topics_seed_key'))
    )
    op.create_table('system_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.Column('source', sa.String(length=60), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_logs'))
    )
    op.create_index('ix_system_logs_created', 'system_logs', ['created_at'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('vocabulary_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=80), nullable=False),
    sa.Column('part_of_speech', sa.String(length=20), nullable=False),
    sa.Column('definition', sa.Text(), nullable=False),
    sa.Column('example', sa.Text(), nullable=False),
    sa.Column('extra_examples', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('synonyms', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('antonyms', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('collocations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('word_family', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('topics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cefr', sa.String(length=4), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('is_academic', sa.Boolean(), nullable=False),
    sa.Column('is_phrase', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vocabulary_items')),
    sa.UniqueConstraint('word', 'part_of_speech', name=op.f('uq_vocabulary_items_word_part_of_speech'))
    )
    op.create_index(op.f('ix_vocabulary_items_word'), 'vocabulary_items', ['word'], unique=False)
    op.create_table('ai_interaction_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('agent', sa.String(length=40), nullable=False),
    sa.Column('task', sa.String(length=40), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('model', sa.String(length=60), nullable=False),
    sa.Column('tier', sa.String(length=10), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_category', sa.String(length=30), nullable=True),
    sa.Column('error_message', sa.String(length=300), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('is_mock', sa.Boolean(), nullable=False),
    sa.Column('debug_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ai_interaction_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_interaction_logs'))
    )
    op.create_index('ix_ai_interaction_logs_created', 'ai_interaction_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_interaction_logs_user_id'), 'ai_interaction_logs', ['user_id'], unique=False)
    op.create_table('auth_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by_id', sa.Integer(), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_auth_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_sessions')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_auth_sessions_token_hash'))
    )
    op.create_index(op.f('ix_auth_sessions_user_id'), 'auth_sessions', ['user_id'], unique=False)
    op.create_table('daily_missions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('focus', sa.String(length=60), nullable=True),
    sa.Column('tasks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('bonus_xp', sa.Integer(), nullable=False),
    sa.Column('bonus_awarded', sa.Boolean(), nullable=False),
    sa.Column('generated_by', sa.String(length=20), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_daily_missions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_missions')),
    sa.UniqueConstraint('user_id', 'day', name=op.f('uq_daily_missions_user_id_day'))
    )
    op.create_index(op.f('ix_daily_missions_user_id'), 'daily_missions', ['user_id'], unique=False)
    op.create_table('diagnostic_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('items', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('answers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('section_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('writing_sample', sa.Text(), nullable=False),
    sa.Column('writing_band', sa.Float(), nullable=True),
    sa.Column('speaking_sample', sa.Text(), nullable=True),
    sa.Column('speaking_band', sa.Float(), nullable=True),
    sa.Column('estimated_cefr', sa.String(length=4), nullable=True),
    sa.Column('estimated_band', sa.Float(), nullable=True),
    sa.Column('skill_estimates', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_diagnostic_attempts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_diagnostic_attempts'))
    )
    op.create_index(op.f('ix_diagnostic_attempts_user_id'), 'diagnostic_attempts', ['user_id'], unique=False)
    op.create_table('learner_skill_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('skill', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('band', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('trend', sa.String(length=12), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('recent', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_practiced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_learner_skill_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_learner_skill_profiles')),
    sa.UniqueConstraint('user_id', 'skill', name=op.f('uq_learner_skill_profiles_user_id_skill'))
    )
    op.create_index(op.f('ix_learner_skill_profiles_user_id'), 'learner_skill_profiles', ['user_id'], unique=False)
    op.create_table('learning_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('goal_type', sa.String(length=30), nullable=False),
    sa.Column('skill', sa.String(length=20), nullable=True),
    sa.Column('target_value', sa.Float(), nullable=True),
    sa.Column('target_label', sa.String(length=100), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('achieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_learning_goals_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_learning_goals'))
    )
    op.create_index(op.f('ix_learning_goals_user_id'), 'learning_goals', ['user_id'], unique=False)
    op.create_table('listening_scripts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seed_key', sa.String(length=80), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('topic', sa.String(length=60), nullable=False),
    sa.Column('scenario', sa.String(length=20), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('speakers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('segments', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('speech_rate', sa.Float(), nullable=False),
    sa.Column('accent', sa.String(length=20), nullable=False),
    sa.Column('context', sa.Text(), nullable=False),
    sa.Column('audio_status', sa.String(length=10), nullable=False),
    sa.Column('audio', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('quality', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('target_vocabulary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_for_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_for_user_id'], ['users.id'], name=op.f('fk_listening_scripts_created_for_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_listening_scripts')),
    sa.UniqueConstraint('seed_key', name=op.f('uq_listening_scripts_seed_key'))
    )
    op.create_index(op.f('ix_listening_scripts_created_for_user_id'), 'listening_scripts', ['created_for_user_id'], unique=False)
    op.create_index(op.f('ix_listening_scripts_topic'), 'listening_scripts', ['topic'], unique=False)
    op.create_table('mistakes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('subcategory', sa.String(length=40), nullable=False),
    sa.Column('original', sa.Text(), nullable=False),
    sa.Column('corrected', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('signature', sa.String(length=200), nullable=False),
    sa.Column('occurrences', sa.Integer(), nullable=False),
    sa.Column('repeated', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('ref_type', sa.String(length=30), nullable=True),
    sa.Column('ref_id', sa.Integer(), nullable=True),
    sa.Column('practice_attempts', sa.Integer(), nullable=False),
    sa.Column('practice_correct', sa.Integer(), nullable=False),
    sa.Column('practice_streak', sa.Integer(), nullable=False),
    sa.Column('last_practiced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revisit_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mastered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_mistakes_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mistakes'))
    )
    op.create_index('ix_mistakes_user_last_seen', 'mistakes', ['user_id', 'last_seen_at'], unique=False)
    op.create_index('ix_mistakes_user_signature', 'mistakes', ['user_id', 'signature'], unique=False)
    op.create_index('ix_mistakes_user_status', 'mistakes', ['user_id', 'status'], unique=False)
    op.create_index('ix_mistakes_user_subcategory', 'mistakes', ['user_id', 'subcategory'], unique=False)
    op.create_table('practice_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('why', sa.Text(), nullable=False),
    sa.Column('focus', sa.String(length=40), nullable=True),
    sa.Column('items', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('mistake_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('results', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_practice_sets_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_practice_sets'))
    )
    op.create_index('ix_practice_sets_user_created', 'practice_sets', ['user_id', 'created_at'], unique=False)
    op.create_table('profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('goal', sa.String(length=20), nullable=False),
    sa.Column('ielts_module', sa.String(length=20), nullable=False),
    sa.Column('self_reported_level', sa.String(length=20), nullable=False),
    sa.Column('target_band', sa.Float(), nullable=False),
    sa.Column('test_date', sa.Date(), nullable=True),
    sa.Column('daily_minutes', sa.Integer(), nullable=False),
    sa.Column('preferred_mode', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('preferred_topics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('theme', sa.String(length=10), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('keep_recordings', sa.Boolean(), nullable=False),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=False),
    sa.Column('diagnostic_completed', sa.Boolean(), nullable=False),
    sa.Column('estimated_cefr', sa.String(length=4), nullable=True),
    sa.Column('estimated_band', sa.Float(), nullable=True),
    sa.Column('band_confidence', sa.Float(), nullable=False),
    sa.Column('weak_areas', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('strong_areas', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('insights_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_profiles'))
    )
    op.create_table('progress_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('overall_band', sa.Float(), nullable=True),
    sa.Column('cefr', sa.String(length=4), nullable=True),
    sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('vocab_known', sa.Integer(), nullable=False),
    sa.Column('vocab_mastered', sa.Integer(), nullable=False),
    sa.Column('mistakes_open', sa.Integer(), nullable=False),
    sa.Column('xp_total', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_progress_snapshots_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_progress_snapshots')),
    sa.UniqueConstraint('user_id', 'day', name=op.f('uq_progress_snapshots_user_id_day'))
    )
    op.create_index(op.f('ix_progress_snapshots_user_id'), 'progress_snapshots', ['user_id'], unique=False)
    op.create_table('reading_passages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seed_key', sa.String(length=80), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('topic', sa.String(length=60), nullable=False),
    sa.Column('module', sa.String(length=20), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('paragraphs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('headings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=False),
    sa.Column('target_vocabulary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('quality', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_for_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_for_user_id'], ['users.id'], name=op.f('fk_reading_passages_created_for_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reading_passages')),
    sa.UniqueConstraint('seed_key', name=op.f('uq_reading_passages_seed_key'))
    )
    op.create_index(op.f('ix_reading_passages_created_for_user_id'), 'reading_passages', ['created_for_user_id'], unique=False)
    op.create_index(op.f('ix_reading_passages_topic'), 'reading_passages', ['topic'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rule', sa.String(length=60), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('why', sa.Text(), nullable=False),
    sa.Column('priority', sa.Float(), nullable=False),
    sa.Column('signals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('action', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_recommendations_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendations'))
    )
    op.create_index('ix_recommendations_user_status', 'recommendations', ['user_id', 'status'], unique=False)
    op.create_table('si_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('signal', sa.String(length=60), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('actions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_si_events_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_si_events'))
    )
    op.create_index('ix_si_events_user_created', 'si_events', ['user_id', 'created_at'], unique=False)
    op.create_table('speaking_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('topic', sa.String(length=120), nullable=False),
    sa.Column('plan', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('current_part', sa.Integer(), nullable=False),
    sa.Column('current_index', sa.Integer(), nullable=False),
    sa.Column('followups_asked', sa.Integer(), nullable=False),
    sa.Column('current_question', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('target_expressions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_speaking_seconds', sa.Float(), nullable=False),
    sa.Column('failure_reason', sa.String(length=300), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_speaking_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_speaking_sessions'))
    )
    op.create_index('ix_speaking_sessions_user_created', 'speaking_sessions', ['user_id', 'created_at'], unique=False)
    op.create_table('streaks',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('current', sa.Integer(), nullable=False),
    sa.Column('longest', sa.Integer(), nullable=False),
    sa.Column('last_active_day', sa.Date(), nullable=True),
    sa.Column('freezes', sa.Integer(), nullable=False),
    sa.Column('freezes_used', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_streaks_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_streaks'))
    )
    op.create_table('study_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('activity', sa.String(length=30), nullable=False),
    sa.Column('ref_type', sa.String(length=30), nullable=True),
    sa.Column('ref_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('xp_earned', sa.Integer(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_study_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_study_sessions'))
    )
    op.create_index('ix_study_sessions_user_started', 'study_sessions', ['user_id', 'started_at'], unique=False)
    op.create_table('tutor_conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('scenario', sa.String(length=60), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_tutor_conversations_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tutor_conversations'))
    )
    op.create_index('ix_tutor_conversations_user_updated', 'tutor_conversations', ['user_id', 'updated_at'], unique=False)
    op.create_table('user_achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('achievement_id', sa.Integer(), nullable=False),
    sa.Column('earned_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], name=op.f('fk_user_achievements_achievement_id_achievements'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_achievements_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_achievements')),
    sa.UniqueConstraint('user_id', 'achievement_id', name=op.f('uq_user_achievements_user_id_achievement_id'))
    )
    op.create_index(op.f('ix_user_achievements_user_id'), 'user_achievements', ['user_id'], unique=False)
    op.create_table('user_challenges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('week', sa.String(length=10), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('metric', sa.String(length=40), nullable=False),
    sa.Column('target', sa.Integer(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('xp_reward', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_challenges_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_challenges')),
    sa.UniqueConstraint('user_id', 'week', 'code', name=op.f('uq_user_challenges_user_id_week_code'))
    )
    op.create_index(op.f('ix_user_challenges_user_id'), 'user_challenges', ['user_id'], unique=False)
    op.create_table('user_vocabulary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=10), nullable=False),
    sa.Column('ease', sa.Float(), nullable=False),
    sa.Column('interval_days', sa.Float(), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('incorrect_count', sa.Integer(), nullable=False),
    sa.Column('streak', sa.Integer(), nullable=False),
    sa.Column('lapses', sa.Integer(), nullable=False),
    sa.Column('avg_response_ms', sa.Integer(), nullable=True),
    sa.Column('used_in_writing', sa.Integer(), nullable=False),
    sa.Column('used_in_speaking', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Float(), nullable=False),
    sa.Column('reason', sa.String(length=30), nullable=False),
    sa.Column('reason_detail', sa.String(length=300), nullable=True),
    sa.Column('last_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['vocabulary_items.id'], name=op.f('fk_user_vocabulary_item_id_vocabulary_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_vocabulary_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_vocabulary')),
    sa.UniqueConstraint('user_id', 'item_id', name=op.f('uq_user_vocabulary_user_id_item_id'))
    )
    op.create_index('ix_user_vocabulary_due', 'user_vocabulary', ['user_id', 'due_at'], unique=False)
    op.create_index(op.f('ix_user_vocabulary_item_id'), 'user_vocabulary', ['item_id'], unique=False)
    op.create_table('writing_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_type', sa.String(length=10), nullable=False),
    sa.Column('module', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('topic', sa.String(length=60), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=False),
    sa.Column('visual', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('key_points', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('min_words', sa.Integer(), nullable=False),
    sa.Column('time_limit_minutes', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('seed_key', sa.String(length=80), nullable=True),
    sa.Column('created_for_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_for_user_id'], ['users.id'], name=op.f('fk_writing_tasks_created_for_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_writing_tasks')),
    sa.UniqueConstraint('seed_key', name=op.f('uq_writing_tasks_seed_key'))
    )
    op.create_index(op.f('ix_writing_tasks_created_for_user_id'), 'writing_tasks', ['created_for_user_id'], unique=False)
    op.create_table('xp_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=40), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('ref_type', sa.String(length=40), nullable=True),
    sa.Column('ref_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_xp_transactions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_xp_transactions'))
    )
    op.create_index('ix_xp_transactions_user_created', 'xp_transactions', ['user_id', 'created_at'], unique=False)
    op.create_table('listening_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('script_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('question_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('time_limit_minutes', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('answers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('results', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('correct', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('band', sa.Float(), nullable=True),
    sa.Column('replays', sa.Integer(), nullable=False),
    sa.Column('transcript_viewed', sa.Boolean(), nullable=False),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['script_id'], ['listening_scripts.id'], name=op.f('fk_listening_attempts_script_id_listening_scripts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_listening_attempts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_listening_attempts'))
    )
    op.create_index(op.f('ix_listening_attempts_script_id'), 'listening_attempts', ['script_id'], unique=False)
    op.create_index('ix_listening_attempts_user_started', 'listening_attempts', ['user_id', 'started_at'], unique=False)
    op.create_table('listening_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('script_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('qtype', sa.String(length=30), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('answer', sa.String(length=300), nullable=False),
    sa.Column('accepted', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('word_limit', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['script_id'], ['listening_scripts.id'], name=op.f('fk_listening_questions_script_id_listening_scripts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_listening_questions'))
    )
    op.create_index(op.f('ix_listening_questions_script_id'), 'listening_questions', ['script_id'], unique=False)
    op.create_table('reading_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('passage_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('question_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('time_limit_minutes', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('answers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('results', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('correct', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('band', sa.Float(), nullable=True),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['passage_id'], ['reading_passages.id'], name=op.f('fk_reading_attempts_passage_id_reading_passages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_reading_attempts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reading_attempts'))
    )
    op.create_index(op.f('ix_reading_attempts_passage_id'), 'reading_attempts', ['passage_id'], unique=False)
    op.create_index('ix_reading_attempts_user_started', 'reading_attempts', ['user_id', 'started_at'], unique=False)
    op.create_table('reading_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('passage_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('qtype', sa.String(length=30), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('answer', sa.String(length=300), nullable=False),
    sa.Column('accepted', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('evidence_paragraph', sa.String(length=4), nullable=True),
    sa.Column('word_limit', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['passage_id'], ['reading_passages.id'], name=op.f('fk_reading_questions_passage_id_reading_passages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reading_questions'))
    )
    op.create_index(op.f('ix_reading_questions_passage_id'), 'reading_questions', ['passage_id'], unique=False)
    op.create_table('speaking_evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('overall_band', sa.Float(), nullable=False),
    sa.Column('fluency_coherence', sa.Float(), nullable=False),
    sa.Column('lexical_resource', sa.Float(), nullable=False),
    sa.Column('grammatical_range_accuracy', sa.Float(), nullable=False),
    sa.Column('pronunciation', sa.Float(), nullable=True),
    sa.Column('pronunciation_note', sa.Text(), nullable=False),
    sa.Column('criteria_feedback', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('hesitation', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('repeated_words', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fillers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('grammar_patterns', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('strengths', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('weaknesses', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recommendations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expressions_used', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('model', sa.String(length=60), nullable=False),
    sa.Column('is_mock', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['speaking_sessions.id'], name=op.f('fk_speaking_evaluations_session_id_speaking_sessions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_speaking_evaluations_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_speaking_evaluations')),
    sa.UniqueConstraint('session_id', name=op.f('uq_speaking_evaluations_session_id'))
    )
    op.create_index(op.f('ix_speaking_evaluations_user_id'), 'speaking_evaluations', ['user_id'], unique=False)
    op.create_table('speaking_transcripts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('part', sa.Integer(), nullable=False),
    sa.Column('turn_index', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('is_followup', sa.Boolean(), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=False),
    sa.Column('transcript_source', sa.String(length=10), nullable=False),
    sa.Column('audio_key', sa.String(length=255), nullable=True),
    sa.Column('audio_mime', sa.String(length=60), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('stt_confidence', sa.Float(), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['speaking_sessions.id'], name=op.f('fk_speaking_transcripts_session_id_speaking_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_speaking_transcripts'))
    )
    op.create_index(op.f('ix_speaking_transcripts_session_id'), 'speaking_transcripts', ['session_id'], unique=False)
    op.create_table('tutor_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['tutor_conversations.id'], name=op.f('fk_tutor_messages_conversation_id_tutor_conversations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tutor_messages'))
    )
    op.create_index(op.f('ix_tutor_messages_conversation_id'), 'tutor_messages', ['conversation_id'], unique=False)
    op.create_table('vocabulary_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('user_vocab_id', sa.Integer(), nullable=False),
    sa.Column('exercise_type', sa.String(length=30), nullable=False),
    sa.Column('correct', sa.Boolean(), nullable=False),
    sa.Column('answer', sa.String(length=300), nullable=False),
    sa.Column('response_ms', sa.Integer(), nullable=True),
    sa.Column('quality', sa.Integer(), nullable=False),
    sa.Column('state_before', sa.String(length=10), nullable=False),
    sa.Column('state_after', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['vocabulary_items.id'], name=op.f('fk_vocabulary_reviews_item_id_vocabulary_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_vocabulary_reviews_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_vocab_id'], ['user_vocabulary.id'], name=op.f('fk_vocabulary_reviews_user_vocab_id_user_vocabulary'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vocabulary_reviews'))
    )
    op.create_index('ix_vocabulary_reviews_user_created', 'vocabulary_reviews', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_vocabulary_reviews_user_vocab_id'), 'vocabulary_reviews', ['user_vocab_id'], unique=False)
    op.create_table('writing_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=10), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('hints_used', sa.Integer(), nullable=False),
    sa.Column('tutor_notes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('failure_reason', sa.String(length=300), nullable=True),
    sa.Column('autosaved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['writing_tasks.id'], name=op.f('fk_writing_submissions_task_id_writing_tasks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_writing_submissions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_writing_submissions'))
    )
    op.create_index(op.f('ix_writing_submissions_task_id'), 'writing_submissions', ['task_id'], unique=False)
    op.create_index('ix_writing_submissions_user_created', 'writing_submissions', ['user_id', 'created_at'], unique=False)
    op.create_table('writing_evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('overall_band', sa.Float(), nullable=False),
    sa.Column('task_response', sa.Float(), nullable=False),
    sa.Column('coherence_cohesion', sa.Float(), nullable=False),
    sa.Column('lexical_resource', sa.Float(), nullable=False),
    sa.Column('grammatical_range_accuracy', sa.Float(), nullable=False),
    sa.Column('criteria_feedback', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('strengths', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('weaknesses', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('task_response_issues', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cohesion_issues', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('vocabulary_issues', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('advice', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('recommended_exercise', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('model', sa.String(length=60), nullable=False),
    sa.Column('is_mock', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['writing_submissions.id'], name=op.f('fk_writing_evaluations_submission_id_writing_submissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_writing_evaluations_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_writing_evaluations')),
    sa.UniqueConstraint('submission_id', name=op.f('uq_writing_evaluations_submission_id'))
    )
    op.create_index(op.f('ix_writing_evaluations_user_id'), 'writing_evaluations', ['user_id'], unique=False)
    op.create_table('writing_errors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evaluation_id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mistake_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('subcategory', sa.String(length=40), nullable=False),
    sa.Column('original', sa.Text(), nullable=False),
    sa.Column('corrected', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('start_offset', sa.Integer(), nullable=True),
    sa.Column('end_offset', sa.Integer(), nullable=True),
    sa.Column('repeated', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_id'], ['writing_evaluations.id'], name=op.f('fk_writing_errors_evaluation_id_writing_evaluations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mistake_id'], ['mistakes.id'], name=op.f('fk_writing_errors_mistake_id_mistakes'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submission_id'], ['writing_submissions.id'], name=op.f('fk_writing_errors_submission_id_writing_submissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_writing_errors_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_writing_errors'))
    )
    op.create_index(op.f('ix_writing_errors_evaluation_id'), 'writing_errors', ['evaluation_id'], unique=False)
    op.create_index(op.f('ix_writing_errors_submission_id'), 'writing_errors', ['submission_id'], unique=False)
    op.create_index(op.f('ix_writing_errors_user_id'), 'writing_errors', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_writing_errors_user_id'), table_name='writing_errors')
    op.drop_index(op.f('ix_writing_errors_submission_id'), table_name='writing_errors')
    op.drop_index(op.f('ix_writing_errors_evaluation_id'), table_name='writing_errors')
    op.drop_table('writing_errors')
    op.drop_index(op.f('ix_writing_evaluations_user_id'), table_name='writing_evaluations')
    op.drop_table('writing_evaluations')
    op.drop_index('ix_writing_submissions_user_created', table_name='writing_submissions')
    op.drop_index(op.f('ix_writing_submissions_task_id'), table_name='writing_submissions')
    op.drop_table('writing_submissions')
    op.drop_index(op.f('ix_vocabulary_reviews_user_vocab_id'), table_name='vocabulary_reviews')
    op.drop_index('ix_vocabulary_reviews_user_created', table_name='vocabulary_reviews')
    op.drop_table('vocabulary_reviews')
    op.drop_index(op.f('ix_tutor_messages_conversation_id'), table_name='tutor_messages')
    op.drop_table('tutor_messages')
    op.drop_index(op.f('ix_speaking_transcripts_session_id'), table_name='speaking_transcripts')
    op.drop_table('speaking_transcripts')
    op.drop_index(op.f('ix_speaking_evaluations_user_id'), table_name='speaking_evaluations')
    op.drop_table('speaking_evaluations')
    op.drop_index(op.f('ix_reading_questions_passage_id'), table_name='reading_questions')
    op.drop_table('reading_questions')
    op.drop_index('ix_reading_attempts_user_started', table_name='reading_attempts')
    op.drop_index(op.f('ix_reading_attempts_passage_id'), table_name='reading_attempts')
    op.drop_table('reading_attempts')
    op.drop_index(op.f('ix_listening_questions_script_id'), table_name='listening_questions')
    op.drop_table('listening_questions')
    op.drop_index('ix_listening_attempts_user_started', table_name='listening_attempts')
    op.drop_index(op.f('ix_listening_attempts_script_id'), table_name='listening_attempts')
    op.drop_table('listening_attempts')
    op.drop_index('ix_xp_transactions_user_created', table_name='xp_transactions')
    op.drop_table('xp_transactions')
    op.drop_index(op.f('ix_writing_tasks_created_for_user_id'), table_name='writing_tasks')
    op.drop_table('writing_tasks')
    op.drop_index(op.f('ix_user_vocabulary_item_id'), table_name='user_vocabulary')
    op.drop_index('ix_user_vocabulary_due', table_name='user_vocabulary')
    op.drop_table('user_vocabulary')
    op.drop_index(op.f('ix_user_challenges_user_id'), table_name='user_challenges')
    op.drop_table('user_challenges')
    op.drop_index(op.f('ix_user_achievements_user_id'), table_name='user_achievements')
    op.drop_table('user_achievements')
    op.drop_index('ix_tutor_conversations_user_updated', table_name='tutor_conversations')
    op.drop_table('tutor_conversations')
    op.drop_index('ix_study_sessions_user_started', table_name='study_sessions')
    op.drop_table('study_sessions')
    op.drop_table('streaks')
    op.drop_index('ix_speaking_sessions_user_created', table_name='speaking_sessions')
    op.drop_table('speaking_sessions')
    op.drop_index('ix_si_events_user_created', table_name='si_events')
    op.drop_table('si_events')
    op.drop_index('ix_recommendations_user_status', table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_reading_passages_topic'), table_name='reading_passages')
    op.drop_index(op.f('ix_reading_passages_created_for_user_id'), table_name='reading_passages')
    op.drop_table('reading_passages')
    op.drop_index(op.f('ix_progress_snapshots_user_id'), table_name='progress_snapshots')
    op.drop_table('progress_snapshots')
    op.drop_table('profiles')
    op.drop_index('ix_practice_sets_user_created', table_name='practice_sets')
    op.drop_table('practice_sets')
    op.drop_index('ix_mistakes_user_subcategory', table_name='mistakes')
    op.drop_index('ix_mistakes_user_status', table_name='mistakes')
    op.drop_index('ix_mistakes_user_signature', table_name='mistakes')
    op.drop_index('ix_mistakes_user_last_seen', table_name='mistakes')
    op.drop_table('mistakes')
    op.drop_index(op.f('ix_listening_scripts_topic'), table_name='listening_scripts')
    op.drop_index(op.f('ix_listening_scripts_created_for_user_id'), table_name='listening_scripts')
    op.drop_table('listening_scripts')
    op.drop_index(op.f('ix_learning_goals_user_id'), table_name='learning_goals')
    op.drop_table('learning_goals')
    op.drop_index(op.f('ix_learner_skill_profiles_user_id'), table_name='learner_skill_profiles')
    op.drop_table('learner_skill_profiles')
    op.drop_index(op.f('ix_diagnostic_attempts_user_id'), table_name='diagnostic_attempts')
    op.drop_table('diagnostic_attempts')
    op.drop_index(op.f('ix_daily_missions_user_id'), table_name='daily_missions')
    op.drop_table('daily_missions')
    op.drop_index(op.f('ix_auth_sessions_user_id'), table_name='auth_sessions')
    op.drop_table('auth_sessions')
    op.drop_index(op.f('ix_ai_interaction_logs_user_id'), table_name='ai_interaction_logs')
    op.drop_index('ix_ai_interaction_logs_created', table_name='ai_interaction_logs')
    op.drop_table('ai_interaction_logs')
    op.drop_index(op.f('ix_vocabulary_items_word'), table_name='vocabulary_items')
    op.drop_table('vocabulary_items')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_system_logs_created', table_name='system_logs')
    op.drop_table('system_logs')
    op.drop_table('speaking_topics')
    op.drop_index(op.f('ix_grammar_exercises_topic'), table_name='grammar_exercises')
    op.drop_table('grammar_exercises')
    op.drop_table('achievements')
    # ### end Alembic commands ###
